# .travis.yml

language: python
python:
  - "3.11"

install:
  - pip install -r requirements.txt

script:
  - python manage.py test

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
